language: python
dist: trusty
sudo: required

services:
  - docker

before_install:
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confold" --force-yes docker-engine

install:
  # Install the latest Ansible Container and Ansible
  - pip install ansible

script:
  # Make sure docker is functioning
  - docker version
  - docker-compose version
  - docker info

  # Run tests
  - cd tests
  - ansible-playbook test.yml

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
