- name: Remove hostname
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ openshift_hostname }}' 
    state: absent 
  become: yes
  become_user: root
    
- name: Add hostname
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ default_ip_address}}'
    line: "{{ default_ip_address }}  {{ openshift_hostname }}"
  become: yes
  become_user: root

