- name: Check if minishift is running
  command: minishift status
  register: minishift_state

- debug:
    msg: "Minishift is already running. Use minishift_recreate to continue."
  when: minishift_state.stdout == 'Running' and not minishift_recreate

- name: Stop playbook, if running and not recreate
  assert:
    that: true == false
  when: minishift_state.stdout == 'Running' and not minishift_recreate

- debug:
    msg: "Shutting down minishift..."
  when: minishift_state.stdout == 'Running'

- name: Shutdown minishift
  command: minishift stop
  when: minishift_state.stdout == 'Running'

- name: Deleting minishift
  command: minishift delete
  when: minishift_state.stdout == 'Running'

- name: Remove ~/.minishift
  file: 
    path: ~/.minishift
    state: absent
