---
- name: Get the IP address 
  set_fact:
    default_ip_address: "{{ ansible_default_ipv4.address }}"

- name: Check if minishift binary exists
  stat:
    path: "{{ minishift_dest }}/minishift"
  register: minishift_client

- name: Install minishift 
  include: install_client.yml
  when: not minishift_client.stat.exists or minishift_force_install 

- name: Check if running
  include: isrunning.yml 

- name: Run minishift
  command: "minishift {{ minishift_up_options | join(' ') }}"
  register: output         
  ignore_errors: yes

- name: Give cluster-admin to developer
  include: grant_admin.yml 

- name: Set volume path permissions
  command: "minishift ssh chmod 777 {{ minishift_volume['path'] }}"

- name: Create objects
  include: create_objects.yml
