---
- name: Get the IP address 
  set_fact:
    default_ip_address: "{{ ansible_default_ipv4.address }}"

- name: Check if minishift binary exists
  stat:
    path: "{{ minishift_dest }}/minishift"
  register: minishift_client

- name: Install minishift 
  include: install_client.yml
  when: not minishift_client.stat.exists or minishift_force_install 

- name: Check if running
  include: isrunning.yml 

- name: Run minishift
  command: "minishift start --{{ minishift_start_options | join(' --') }}"
  register: output         

- name: Give cluster-admin to developer
  include: grant_admin.yml 

- name: Create volume path
  command: minishift ssh "sudo mkdir -m 0777 -p {{ minishift_volume['path'] }}"

- name: Set volume ownership
  command: minishift ssh "sudo chown docker:staff {{ minishift_volume['path'] }}"

- name: Create objects
  include: create_objects.yml

- name: Show output
  debug:
    var: output.stdout_lines

