---
- name: Install Docker machine driver 
  include: "{{ ansible_os_family }}_driver.yml"

- name: Check if oc binary exists
  stat:
    path: "{{ openshift_client_dest }}/oc" 
  register: oc_client

- name: Install the oc client
  include: install_oc.yml
  when: not oc_client.stat.exists or openshift_force_client_install 

- name: Check if minishift binary exists
  stat:
    path: "{{ minishift_dest }}/minishift"
  register: minishift_client

- name: Install minishift 
  include: install_minishift.yml
  when: not minishift_client.stat.exists or minishift_force_install 

- name: Check if running
  include: isrunning.yml 

- name: Create a temp dir
  command: mktemp -d -t ansible.XXXXXXXXXX
  register: start_temp 

- name: Run minishift
  command: "minishift start --{{ minishift_start_options | join(' --') }}"
  register: minishift_out

- name: Give cluster-admin to developer
  include: grant_admin.yml 

- name: Create vol path
  include: create_vol_path.yml

- name: Create objects
  include: create_objects.yml

- name: Filter start output
  include: filter_output.yml

- name: Show output
  debug:
    var: filtered_output.stdout_lines 

