
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ openshift_volume_name }} 
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ openshift_volume_path }} 
